export const SIGNUP_REQUEST ='SIGNUP_REQUEST';
export const LOGIN_REQUEST ='LOGIN_REQUEST';
export const UPDATE_REQUEST ='UPDATE_REQUEST';
export const DELETE_REQUEST ='DELETE_REQUEST';
export const LANGUAGE_REQUEST ='LANGUAGE_REQUEST';