export const SIGNUP_REQUEST ='SIGNUP_REQUEST';
export const LOGIN_REQUEST ='LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LANGUAGE_REQUEST ='LANGUAGE_REQUEST';
export const LEVEL_REQUEST ='LEVEL_REQUEST';
export const LEVELCONTENT_REQUEST = 'LEVELCONTENT_REQUEST';
export const SETUSERPROGRESS = 'SETUSERPROGRESS';
export const UPDATEUSERPROG_REQUEST = 'UPDATEUSERPROG_REQUEST';